### ISSUE TITLE
MissingPluginException when doing addDoc

### ISSUE THREAD

**Issue by GroovinChip** [AppleEducate/fb_firestore#1]
Full code snippet:
```
try {
  FbFirestore.addDoc('Trains', {
    'DepartureTime': departureTime.toString(),
    'Recurring': isRecurring,
  });
} catch (e) {
  print(e);
} finally {
  Navigator.pop(context);
}
```

Full stack trace:
```
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(144)] Unhandled Exception: MissingPluginException(No implementation found for method DocumentReference#setData on channel plugins.flutter.io/cloud_firestore)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      DocumentReference.setData (package:cloud_firestore/src/document_reference.dart:51:30)
#2      CollectionReference.add (package:cloud_firestore/src/collection_reference.dart:58:23)
<asynchronous suspension>
#3      FbFirestore.addDoc (package:fb_firestore/mobile.dart:31:39)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      FbFirestore.addDoc (package:fb_firestore/mobile.dart:30:23)
#6      _NewCoffeeTrainState.build.<anonymous closure> (package:drcc_coffee_train/new_coffee_train.dart:86:25)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:701:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:783:36)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
#13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#19     _rootRunUnary (dart:async/zone.dart:1136:13)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _invoke1 (dart:ui/hooks.dart:273:10)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

**Comment by rodydavis** [comment]
Have you added the set up code? Like the google-info.plist

**Comment by GroovinChip** [comment]
I added the set up for Android because I'm not ready for iOS yet. Do they
both need to be there in order for it to work on one mobile platform? (I
don't have a Mac so I do iOS last)

**Comment by rodydavis** [comment]
No, but the android definitely  needs to be set up. Also paste the full code snippet if you can. Or at least the imports

**Comment by GroovinChip** [comment]
Yeah so I had already set up the Android stuff, added the required lines in the gradle files, downloaded the google-services.json

imports:
```
import 'package:datetime_picker_formfield/datetime_picker_formfield.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:fb_firestore/fb_firestore.dart';
```

The code I pasted in the initial message is the entirety of the code within the `onPressed` of a FAB.
